# Generated by Django 3.1.7 on 2021-03-06 21:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('autentikasi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tgl_lahir',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
