# Generated by Django 3.1.7 on 2021-03-06 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autentikasi', '0002_auto_20210306_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tgl_lahir',
            field=models.DateField(null=True),
        ),
    ]
